navigate:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: mvave
    page:
      required: true
      example: living_room
      selector:
        text:

focus:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: mvave
    entity_id:
      required: true
      example: light.ceiling_lights
      selector:
        entity:

home:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: mvave

send_raw:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: mvave
    data:
      required: true
      example: "99 24 05"
      selector:
        text:

press_slot:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: mvave
    slot:
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 16
          mode: box
    action:
      required: false
      default: tap
      selector:
        select:
          options:
            - tap
            - hold

get_pages:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: mvave
    page:
      required: false
      example: living_room
      selector:
        text:
