navigate:
  target:
    device:
      integration: mvave
  fields:
    page:
      required: true
      example: living_room
      selector:
        text:

focus:
  target:
    device:
      integration: mvave
  fields:
    entity_id:
      required: true
      example: light.ceiling_lights
      selector:
        entity:

home:
  target:
    device:
      integration: mvave

send_raw:
  target:
    device:
      integration: mvave
  fields:
    data:
      required: true
      example: "99 24 05"
      selector:
        text:
